---
-
  name: add repo
  apt_repository: repo=ppa:ondrej/php5

-
  name: install apache if not present
  apt: name=apache2 state=present

-
  name: make sure apache is running
  service: name=apache2 state=started enabled=true

# -
#   name: create /var/www/sites
#   file: path=/var/www/sites
#         state=directory
#         owner=apache
#         group=apache

# -
#   name: copy apache's main configuration file
#   template: src=httpd.conf dest=/etc/httpd/conf/httpd.conf
#   notify: restart apache

-
  name: EnableSendFile off in apache.conf
  when: env == 'local'
  lineinfile: line="EnableSendfile off"
              dest=/etc/apache2/apache2.conf
  notify: restart apache
- debug: msg=register apache variable
  register: apache
