---
- include: php.yml
  when: php_is_installed is not defined
- include: apache.yml
  when: apache is not defined
- include: add_jourfixe.yml
# - include: install_modules.yml
#   when: modules is defined
# - include: add_virtual_server.yml
#   when: virtual_server is defined
