 # # Add repos at webtatic
  -
    name: Add webtatic keys
    rpm_key: state=present key=http://repo.webtatic.com/yum/RPM-GPG-KEY-webtatic-andy

  -
    name: Add repo from webtatic.com
    command: rpm -Uvh http://mirror.webtatic.com/yum/el6/latest.rpm
    ignore_errors: True

  -
    copy: src=webtatic.repo
          dest=/etc/yum.repos.d/

  -
    name: install PHP55 packages
    yum: name={{ item }} state=present
    with_items:
      - php55w
      - php55w-mysql
      - php55w-mcrypt
      - php55w-gd

  -
    file: path=/etc/php/conf.d state=directory
    register: php_is_installed=set

  -
    copy: src=php-site.ini dest=/etc/php/conf.d/php-site.ini
    when: env=='local'
    notify: restart apache
