-
  debug: var=php_is_installed

-
  name: add repo
  apt_repository: repo=ppa:ondrej/php5

-
  name: install PHP5 packages
  apt: name={{ item }} state=present
  with_items:
    - php5

# -
# file: path=/etc/php/conf.d state=directory
# register: php_is_installed

# -
# copy: src=php-site.ini dest=/etc/php/conf.d/php-site.ini
# when: env=='local'
# notify: restart apache
