---
- name: restart apache
  action: service name=httpd state=restarted
- name: restart mysql
  service: name=mysql state=restarted
-
  name: restart crond
  service: name=crond state=restarted
-
  name: restart dovecot
  service: name=dovecot state=restarted
