---
- include: tools.yml
- include: dotfiles.yml user={{ ansible_ssh_user }} dotfiles_dest=/home/{{ ansible_ssh_user }}
-
  name: copy timezone info
  command: cp /usr/share/zoneinfo/Europe/Berlin /etc/localtime
-
  name: set /etc/crontab
  copy: src=crontab
        dest=/etc/
-
  name: start cron
  service: name=cron state=started
