---
- debug: var=dotfiles_dest
-
  name: clear .dotfiles
  command: rm -rf /home/{{ansible_ssh_user}}/.dotfiles
  sudo: True
-
  name: get .dotfiles from github repo
  git:  repo=https://github.com/schuppo/dotfiles.git
        dest={{ dotfiles_dest | default('/root') }}/.dotfiles  #added in ansible 1.5
  sudo: True
-
  name: change ownership of .dotfiles directory
  file: path=/home/vagrant/.dotfiles
        state=directory
        owner={{ ansible_ssh_user | default('root') }}
        group={{ ansible_ssh_user | default('root') }}
        recurse=true
  sudo: True
-
  name:   change url of git's origin
  shell:  git remote set-url origin https://schuppo@github.com/schuppo/dotfiles.git
          chdir=~/.dotfiles
  sudo: False
-
  name: bootstrap .dotfiles
  pause: prompt="cd ~/.dotfiles&&script/bootstrap&&chsh"
