---
<<<<<<< HEAD
- include: basic.yml

- include: mysql.yml
- include: python.yml
- include: postfix.yml
- include: apache.yml
- include: modoboa.yml
- include: amavis.yml
=======
- include: sshfs.yml
# - include: basic.yml
# - include: mysql.yml
# - include: python.yml
# - include: postfix.yml
# - include: modoboa.yml
# - include: amavis.yml
>>>>>>> 21c835baf8df8d479dd813fe6cc5d37ddd958a21

