---
-
  name: install tools
  sudo: True
  apt: name={{ item }} state=present update_cache=yes
  with_items:
      - rubygems
      - git-core
      - curl
      - unzip
      - vim
      - zsh
      - ctags
      - bzip2
