---
-
  name: create mysql user for amavis
  mysql_user: name=amavis
              host={{ item }}
              password=amavis priv=*.*:ALL,GRANT
              login_user=root
              login_password=
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
-
  name: create amavis database
  mysql_db: name={{ item }}
            state=present
  with_items:
    - amavis

