---
-
  name: open port
  command: bash /vagrant/ansible/scripts/firewall_add_port_80.sh
-
  name: install apache if not present
  yum: name=httpd state=present

-
  name: make sure apache is running
  service: name=httpd state=started enabled=true

-
  file: path=/etc/httpd/conf.d/virtual_hosts state=directory

-
  file: path=/var/www/sites
        state=directory
        owner=apache
        group=apache
-
  template: src=/vagrant/ansible/templates/fqdn.conf dest=/etc/httpd/conf.d/fqdn.conf
  notify: restart apache

-
  template: src=/vagrant/ansible/templates/httpd.conf dest=/etc/httpd/conf/httpd.conf
  notify: restart apache

-
  template: src=/vagrant/ansible/templates/nosendfile.conf dest=/etc/httpd/conf.d/nosendfile.conf
  notify: restart apache
