---
-
  name: get .dotfiles from github repo
  git:  repo=https://github.com/schuppo/dotfiles.git
        dest=/home/vagrant/.dotfiles
        #accept_hostkey=yes #added in ansible 1.5
  ignore_errors: True
  sudo: False

-
  name:  change ownership of .dotfiles directory
  file: path=/home/vagrant/.dotfiles
        state=directory
        owner=vagrant
        group=vagrant
        recurse=true
  sudo: True

-
  name: bootstrap .dotfiles
  shell:  chdir=/home/vagrant/.dotfiles
          ./script/bootstrap <<< $'vagrant\nO'
  sudo: False
