---
-
  name: install modoboa
  command:  pip install modoboa
            creates=/usr/bin/modoboa-admin.py
-
  name: create mysql databases
  mysql_db: name={{ item }}
            state=present
  with_items:
    - modoboa
-
  name: run modoboa
  shell:    modoboa-admin.py deploy modoboa_server --syncdb --collectstatic --with-amavis --dburl mysql://modoboa:modoboa@localhost/modoboa --amavis_dburl mysql://amavis:amavis@localhost/amavis --domain localhost
            chdir=/var/www/sites
  sudo: False
-
  name: create mysql user
  mysql_user: name=modoboa
              host={{ item }}
              password=modoboa priv=*.*:ALL,GRANT
              login_user=root
              login_password=
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
-
  name: install mod_wsgi and mod_python for apache if not present
  yum: name={{ item }} state=present
  with_items:
    - mod_wsgi
    - mod_python
-
  name: copy modoboa-server.conf
  copy: src=/vagrant/ansible/templates/modoboa-server.conf
        dest=/etc/httpd/conf.d/
  notify: restart apache
