---
-
  name: install modoboa
  command:  pip install modoboa
            creates=/usr/bin/modoboa-admin.py
-
  name: check if modoboa app exists already
  stat: path=/var/www/sites/{{ modoboa_name }}
  register: modoboaDir
-
  name: run modoboa
  when: modoboaDir.stat.isdir is undefined
  shell: modoboa-admin.py deploy {{ modoboa_name }} --syncdb --collectstatic --with-amavis --dburl {{ database_type }}://{{ database_user }}:{{ database_password }}@localhost/{{ database_name }} --amavis_dburl mysql://amavis:amavis@localhost/amavis --domain localhost
            chdir=/var/www/sites
  sudo: False
-
  name: change owner of modoboaDir and files
  file: path=/var/www/sites/{{ modoboa_name }}
        owner=apache group=apache
        recurse=yes
        state=directory
-
  name: install mod_wsgi and mod_python for apache if not present
  yum: name={{ item }} state=present
  with_items:
    - mod_wsgi
-
  name: copy modoboa-server.conf
  template: src=/vagrant/ansible/templates/modoboa-server.conf
            dest=/etc/httpd/conf.d/
  notify: restart apache
-
  name: add modoboa to postfix's cronjobs
  command: bash /vagrant/ansible/scripts/add_modoboa_cron_jobs.sh {{ modoboa_name }}
  notify: restart crond
-
  name: check if sql-domains.cf exists
  stat: path=/etc/postfix/sql-domains.cf
  register: sqlDomainsExists
-
  name: run script if /etc/postfix/sql-domains.cf doesn't exist yet
  when: sqlDomainsExists.stat.isfile is undefined
  shell: modoboa-admin.py postfix_maps --dbtype mysql /etc/postfix <<< $'localhost\n{{ database_name }}\n{{ database_user }}\n'
