---
-
  name: install python if not present
  yum: name=iptables state=present

-
  name: install python requirements via yum
  yum: name={{ item }} state=present
  with_items:
    - python-devel
    - python-pip
    - python-setuptools
    - python-setuptools-devel
    - gcc
    - libxml2-devel
    - libxslt-devel
    - MySQL-python
