---
-
  name: check if modoboa app exists already
  stat: path=/var/www/{{ modoboa_name }}
  register: modoboaDir

-
  name: install modoboa
  when: modoboaDir.stat.isdir is undefined
  shell: modoboa-admin.py deploy {{ modoboa_name }} --syncdb --collectstatic --with-amavis --dburl {{ database_type }}://{{ database_user }}:{{ database_password }}@localhost/{{ database_name }} --amavis_dburl oracle://amavis:amavis@localhost/amavis --domain {{ ansible_domain }}
            chdir=/var/www

# -
#   name: install rrdtool
#   yum: name={{ item }} state=present
#   with_items:
#     - rrdtool
#     - rrdtool-python
# -
#   name: create directory for mail statistics
#   file: state=directory path=/tmp/modoboa
# -
#   name: add modoboa group
#   group: name={{ modoboa_user }} state=present gid={{ modoboa_user_id }}
# -
#   name: add modoboa user
#   user: name={{ modoboa_user }} state=present group={{ modoboa_user }} createhome=no shell=/sbin/nologin uid={{ modoboa_user_id }}

-
  name: copy wsgi.py template
  template: src=wsgi.py dest=/var/www/{{ modoboa_name }}/{{ modoboa_name }}/

-
  name: add modoboa to postfix's cronjobs
  tags: cron
  command: bash /mnt/ansible/scripts/add_modoboa_cron_jobs.sh {{ modoboa_name }} {{ mailbox_owner }}
  notify: restart crond
# -
#   name: check if sql-domains.cf exists
#   stat: path=/etc/postfix/sql-domains.cf
#   register: sqlDomainsExists
# -
#   name: run script if /etc/postfix/sql-domains.cf doesn't exist yet
#   when: sqlDomainsExists.stat.isfile is undefined
#   tags: test
#   shell: modoboa-admin.py postfix_maps --dbtype mysql /etc/postfix <<< $'localhost\n{{ database_name }}\n{{ database_user }}\n'
