---
-
  name: local
  hosts: local
  sudo: True
  remote_user: vagrant
  vars:
    env: local
  vars_prompt:
    -
      name: database_password
      prompt: "Database password"
      private: yes
  roles:
    - common
    # - local

